#!/bin/bash
soubor=TESTY_KOBELKY/TEST_PREHLED
i=1
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "$line"
    echo "________________________________________________________________"
    echo ""

		filename=TESTY_KOBELKY/test_$i
		IFS=$'\n'
		for next in `cat $filename`
		do
    	echo "$next" 
		done
		echo ""
		echo ""
		./IFJ17_compilator <TESTY_KOBELKY/test_$i

    printf "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n\n"

	((i++))
done < "$soubor"




echo "ALL DONE"