#!/bin/bash
soubor=tests/TEST_PREHLED
i=0
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "$line"
    echo "________________________________________________________________"
    echo ""

		filename=tests/test_$i
		IFS=$'\n'
		for next in `cat $filename`
		do
    	echo "$next" 
		done
		echo ""
		echo ""
		./token < tests/test_$i

    printf "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n\n"

	((i++))
done < "$soubor"




echo "ALL DONE"